# Generated by Django 3.0.3 on 2020-08-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToModel',
            new_name='TodoModel',
        ),
    ]
